agt: various

diff --git a/.local/bin/agt b/.local/bin/agt
--- a/.local/bin/agt
+++ b/.local/bin/agt
@@ -35,6 +35,7 @@ rg_preargs=(
     # -M 155 # omit lines longer than 155
 )
 rg_postargs=()
+
 rg_moresearches=()
 
 no_editor=
@@ -42,7 +43,7 @@ search_phrase=
 for arg in "$@"; do
     case $arg in
         -h|-\?|--help)
-            usage 
+            usage
             exit
             ;;
         --debug)
@@ -58,7 +59,7 @@ for arg in "$@"; do
             shift
             rg_moresearches+=("$(printf "%q" "$1")")  # escape it
             ;;
-        *) 
+        *)
             if [[ ! $search_phrase ]]; then
                 search_phrase=$1
             elif [[ $from_pre_to_post ]]; then
@@ -73,6 +74,15 @@ for arg in "$@"; do
     shift
 done
 
+toplevel=$(git rev-parse --show-toplevel 0>&2 2>/dev/null || true)
+if [[ -n "$toplevel" ]]; then
+    if [[ -e "${toplevel}/.rgignore" ]]; then
+        rg_postargs+=(
+            --ignore-file "${toplevel}/.rgignore"
+        )
+    fi
+fi
+
 # set -x
 echo "$search_phrase" >/tmp/agt-query
 rg "$search_phrase" "${rg_preargs[@]}" "${rg_moresearches[@]}" --no-ignore --line-number --ignore-case "${rg_postargs[@]}" >/tmp/agt
@@ -82,6 +92,11 @@ if [[ $? -eq 1 ]]; then
     die "no matches"
 fi
 
+
+if [[ "$(stat --printf="%s" /tmp/agt)" == 0 ]]; then
+    die "> Pattern not found: ${search_phrase}"
+    exit 1
+fi
 
 if [[ ! $no_editor ]]; then
     vi /tmp/agt
