dcot: better error reporting

diff --git a/.local/bin/dcot b/.local/bin/dcot
--- a/.local/bin/dcot
+++ b/.local/bin/dcot
@@ -1,7 +1,11 @@
 #!/bin/bash
-set -eo pipefail
 # runs a shell in the first docker-container/service via docker-compose
+set -eo pipefail
 
+die() {
+    printf '%b\n' "$1" >&2
+    exit "${2-1}"
+}
 find_docker_compose() {
     while [[ $PWD != '/' ]]; do
         result=$PWD/docker-compose.yml
@@ -11,10 +15,12 @@ find_docker_compose() {
         fi
         cd ..
     done
-    echo "could not find docker-compose.yml file" >&2; return 1
+    die "could not find docker-compose.yml file"
 }
 
 docker_compose_file=$(find_docker_compose)
 service=$(yq '.services | to_entries | .[].key' -r < "$docker_compose_file"  )
 
-docker-compose exec "${2:-$service}" "${1:-bash}"
+shell=${1:-bash}
+service=${2:-$service}
+docker-compose exec "$service" "$shell" || die "could not exec $shell in $service"
