various

diff --git a/.local/bin/i3-type-mark b/.local/bin/i3-type-mark
--- a/.local/bin/i3-type-mark
+++ b/.local/bin/i3-type-mark
@@ -1,12 +1,12 @@
 #!/bin/sh
 
 die() {
-  2>&1 echo $1
-  exit 1
+    echo "$*" >&2
+    exit 1
 }
 
 show_help() {
-  cat <<EOF
+    cat <<'EOF'
 usage:
 
   -h/--help      show this message here
@@ -14,71 +14,65 @@ usage:
   -f/--focus     focus at the end
   -k/--key       send a key, e.g.: `ctrl+u` instead of typing
 EOF
-  exit 255
+    exit 255
 }
 
 end_with_cr=1
-focus=
-keys=
+focus=0
+keys=""
 
-arg_pos_1=
 while :; do
-  case $1 in
-    -h|-\?|--help)
-      show_help
-      exit
-      ;;
-    -ne|--no-enter)
-      end_with_cr=
-      ;;
-    -f|--focus)
-      focus=1
-      ;;
-    -k|--key)
-        if [ "$2" ]; then
-            key=$2
+    case ${1-} in
+    -h | -\? | --help)
+        show_help
+        ;;
+    -ne | --no-enter)
+        end_with_cr=0
+        ;;
+    -f | --focus)
+        focus=1
+        ;;
+    -k | --key)
+        if [ -n "${2-}" ]; then
+            keys="$keys $2"
             shift
-            keys=" $keys $key"
         else
-            die  "-k|--key requires a single follow up argument"
+            die "-k|--key requires a single follow up argument"
         fi
         ;;
     --)
-      shift
-      break
-      ;;
+        shift
+        break
+        ;;
     -?*)
-      printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
-      ;;
+        printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
+        ;;
     *)
-      break
-      ;;
-  esac
-
-  shift
+        break
+        ;;
+    esac
+    shift
 done
 
-mark=$1
-2>/dev/null shift || die "can not shift first argument"
+mark=${1-}
+[ -n "$mark" ] || die "missing mark argument"
+shift
 
-window_id=$(i3-msg -t get_tree | jq -r ".. | select(.window?) | select(.marks // [] | contains([\"$mark\"])).window")
-if [ ! "$window_id" ]; then
-  die "can't find mark: $mark"
-fi
+window_id=$(i3-msg -t get_tree | jq -r ".. | select(.window?) | select(.marks // [] | contains([\"$mark\"])).window" | head -n1)
+[ -n "$window_id" ] || die "can't find mark: $mark"
 
-if [ $focus ]; then
-  xdotool windowfocus --sync "$window_id"
+if [ "$focus" -eq 1 ]; then
+    xdotool windowfocus --sync "$window_id"
 fi
 sleep 0.1
 
-for key in $keys ; do
+for key in $keys; do
     xdotool key --clearmodifiers --window "$window_id" "$key"
 done
 
-if [ "$*" ]; then
+if [ "$#" -gt 0 ]; then
     xdotool type --clearmodifiers --window "$window_id" "$*"
-    if [ $end_with_cr ]; then
-      xdotool type --clearmodifiers --window "$window_id" "
-    "
+    if [ "$end_with_cr" -eq 1 ]; then
+        xdotool key --clearmodifiers --window "$window_id" Return
     fi
 fi
